const actionType = {
  SET_USER_FAVORITE_TRACK: 'SET_USER_FAVORITE_TRACK',
  SET_ACTIVE_TAB: 'SET_ACTIVE_TAB',
  SET_USER_ACRONYM: 'SET_USER_ACRONYM',
  SET_REQUEST_BASEURL: 'SET_REQUEST_BASEURL',
  // SET_WAIT_RECEIVE_STATE: 'SET_WAIT_RECEIVE_STATE',
  SET_COPYWRITING_MERGE_TOKEN: 'SET_COPYWRITING_MERGE_TOKEN',
  SET_MODIFY_FILE_CONTENT: 'SET_MODIFY_FILE_CONTENT',
  SET_SEED_USER: 'SET_SEED_USER',
  SET_WAIT_RECEIVE_MAPS: 'SET_WAIT_RECEIVE_MAPS',
  SET_OPEN_TABS: 'SET_OPEN_TABS',
  SET_COOKIES: 'SET_COOKIES'
}

export default actionType
